c_stdlib_version:                # [linux]
  - 2.28                         # [linux]
arm_variant_type:                # [aarch64]
  - sbsa                         # [aarch64]
channel_sources:
  - conda-forge/label/nvpl_rc,conda-forge
channel_targets:
  - conda-forge nvpl_rc
